# Generated by Django 6.0.1 on 2026-02-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(default=' ', upload_to='posts/'),
            preserve_default=False,
        ),
    ]
