# Generated by Django 5.1.1 on 2026-03-13 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={},
        ),
    ]
