# Generated by Django 6.0.1 on 2026-02-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='mime_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
