# Generated by Django 5.1.1 on 2026-03-13 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_follow_unique_together'),
    ]

    operations = [
        # 1. Пропускаем изменение уникальности
        # migrations.AlterUniqueTogether(
        #    name='follow',
        #    unique_together=None,
        # ),
        
        # 2. Комментируем удаление полей именно этой модели
        # migrations.RemoveField(
        #     model_name='follow',
        #     name='follower',
        # ),
        # migrations.RemoveField(
        #     model_name='follow',
        #     name='following',
        # ),

        migrations.RemoveField(
            model_name='media',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        
        # 3. Комментируем само удаление модели Follow
        # migrations.DeleteModel(
        #     name='Follow',
        # ),
        
        migrations.DeleteModel(
            name='Media',
        ),
    ]
