# Generated by Django 5.1.1 on 2026-03-13 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_follow_options_remove_follow_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='media',
            name='mime_type',
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_count_set', to='pages.post'),
        ),
    ]
