# Generated by Django 5.1.1 on 2026-03-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_like_user_comment_media_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='file_url',
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(default='temp.jpg', upload_to='post_media/'),
            preserve_default=False,
        ),
    ]
